services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - .:/app
    command: gunicorn app:app --preload --bind 0.0.0.0:5000 --workers 1


  db:
    image: postgres:15
    restart: unless-stopped
    user: postgres
    ports:
      - 5436:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: quizzy-admin
      POSTGRES_DB: quizzy
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - psql:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quizzy-admin -d quizzy"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: postgres -c log_statement=all -c log_min_duration_statement=0
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

volumes:
  psql: